# Generated by Django 5.2.15 on 2026-06-24 09:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commandes', '0002_alter_cartitem_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FraisLivraison',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('prix_livraison', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Frais de livraison',
                'verbose_name_plural': 'Frais de livraison',
                'db_table': 'livraisons_frais',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['prix_livraison'], name='livraisons__prix_li_ec18f7_idx'), models.Index(fields=['-created_at'], name='livraisons__created_520ed0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('in_transit', 'En transit'), ('delivered', 'Livrée'), ('cancelled', 'Annulée')], db_index=True, default='pending', max_length=20)),
                ('delivery_address', models.TextField(blank=True)),
                ('tracking_number', models.CharField(blank=True, max_length=100)),
                ('estimated_delivery_date', models.DateTimeField(blank=True, null=True)),
                ('actual_delivery_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('delivery_person', models.ForeignKey(blank=True, help_text="L'utilisateur (livreur) en charge de cette livraison.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries_handled', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='commandes.order')),
            ],
            options={
                'verbose_name': 'Livraison',
                'verbose_name_plural': 'Livraisons',
                'db_table': 'livraisons_delivery',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='livraisons__status_dc919a_idx')],
            },
        ),
    ]
