# Generated by Django 5.2.15 on 2026-06-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraisons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fraislivraison',
            name='coordonnee_admin',
            field=models.CharField(default='6.137482, 1.212820', help_text="Coordonnées GPS (latitude, longitude) de l'admin. Par défaut: Lomé.", max_length=255),
        ),
    ]
