# Generated by Django 6.0.6 on 2026-08-05 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livraisons", "0004_delivery_livreur_assigned_history"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="deliverystatushistory",
            new_name="livraisons__deliver_d4bb63_idx",
            old_name="livraisons__deliver_404419_idx",
        ),
        migrations.AddField(
            model_name="delivery",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="L'utilisateur qui a créé cette livraison.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_deliveries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="livreur",
            name="nom",
            field=models.CharField(
                blank=True,
                help_text="Nom de famille du livreur.",
                max_length=100,
                null=True,
                verbose_name="Nom",
            ),
        ),
        migrations.AlterField(
            model_name="livreur",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Informations internes sur le livreur (non visibles du client).",
                null=True,
                verbose_name="Notes internes",
            ),
        ),
        migrations.AlterField(
            model_name="livreur",
            name="prenom",
            field=models.CharField(
                blank=True,
                help_text="Prénom du livreur.",
                max_length=100,
                null=True,
                verbose_name="Prénom",
            ),
        ),
        migrations.AlterField(
            model_name="livreur",
            name="telephone",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Numéro de téléphone principal du livreur.",
                max_length=30,
                null=True,
                verbose_name="Téléphone",
            ),
        ),
        migrations.AlterField(
            model_name="livreur",
            name="type_vehicule",
            field=models.CharField(
                blank=True,
                choices=[
                    ("moto", "Moto"),
                    ("tricycle", "Tricycle"),
                    ("voiture", "Voiture"),
                    ("camionnette", "Camionnette"),
                    ("velo", "Vélo"),
                    ("a_pied", "À pied"),
                ],
                help_text="Type de véhicule utilisé pour les livraisons.",
                max_length=20,
                null=True,
                verbose_name="Type de véhicule",
            ),
        ),
        migrations.AlterField(
            model_name="livreur",
            name="zone_livraison",
            field=models.CharField(
                blank=True,
                help_text="Zone géographique couverte par le livreur (texte libre).",
                max_length=255,
                null=True,
                verbose_name="Zone de livraison",
            ),
        ),
    ]
