# Generated by Django 5.2.15 on 2026-06-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0002_globaltransaction_payment_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PayDunyaWebhookLog',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='webhook_token',
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Dépôt'), ('withdrawal', 'Retrait')], db_index=True, max_length=20),
        ),
    ]
