# Generated by Django 5.2.15 on 2026-06-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0003_delete_paydunyawebhooklog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
