# Generated by Django 5.2.15 on 2026-06-26 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0004_wallet_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='wallet',
            field=models.ForeignKey(blank=True, help_text='Wallet associer (null pour les recharges wallet).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Portefeuille', to='paiements.wallet'),
        ),
    ]
