# Generated by Django 5.2.15 on 2026-06-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0005_payment_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('paydunya', 'PayDunya'), ('stripe', 'Stripe'), ('wallet', 'Portefeuille interne')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Dépôt'), ('withdrawal', 'Retrait'), ('payment', 'Paiement'), ('refund', 'Remboursement'), ('cashback', 'Cashback')], db_index=True, max_length=20),
        ),
    ]
