# Generated by Django 5.2.15 on 2026-07-08 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='conversation',
            new_name='chatbot_con_user_id_d6d938_idx',
            old_name='chatbot_con_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='chatbot_mes_convers_9b53f8_idx',
            old_name='chatbot_mes_convers_idx',
        ),
    ]
