# Generated by Django 5.2.15 on 2026-06-26 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_remove_promocode_max_discount_amount_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PromoUsage',
        ),
    ]
