# Generated by Django 6.0.6 on 2026-08-06 19:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0005_pack_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pack",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="pack",
            name="name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Nom du pack"
            ),
        ),
        migrations.AlterField(
            model_name="packitem",
            name="quantity",
            field=models.PositiveIntegerField(
                blank=True,
                default=1,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Quantité",
            ),
        ),
    ]
