# Generated by Django 5.2.15 on 2026-06-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fidelites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltyprofile',
            name='total_points_earned',
            field=models.PositiveIntegerField(default=0, help_text='Total de points gagnés (lifetime). Jamais décrémenté. Sert au calcul de palier.'),
        ),
    ]
