# Generated by Django 5.2.15 on 2026-06-30 21:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fidelites', '0002_loyaltyprofile_total_points_earned'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyRewardRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.PositiveIntegerField(help_text="Niveau de la règle (ex: 1, 2, 3...) pour l'ordre d'affichage ou de priorité.")),
                ('montant_min', models.DecimalField(decimal_places=2, help_text="Montant minimum d'achat (inclus).", max_digits=12)),
                ('montant_max', models.DecimalField(decimal_places=2, help_text="Montant maximum d'achat (inclus).", max_digits=12)),
                ('nombre_point_gagner', models.PositiveIntegerField(help_text="Nombre de points fixes gagnés pour cette tranche d'achat.")),
                ('is_active', models.BooleanField(default=True, help_text='Règle active ou non.')),
            ],
            options={
                'verbose_name': 'Règle de gain (Bénéfice)',
                'verbose_name_plural': 'Règles de gain (Bénéfices)',
                'db_table': 'loyalty_reward_rules',
                'ordering': ['montant_min'],
            },
        ),
        migrations.CreateModel(
            name='PointValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valeur_un_point_frcfa', models.DecimalField(decimal_places=2, help_text='Valeur correspondante en FCFA.', max_digits=10)),
                ('nombre_de_point', models.PositiveIntegerField(help_text='Quantité de points (ex: 1).')),
                ('duree_validite', models.PositiveIntegerField(default=365, help_text='Durée de validité des points gagnés (en jours).')),
                ('is_active', models.BooleanField(default=True, help_text='Marquer comme configuration active (une seule recommandée).')),
            ],
            options={
                'verbose_name': 'Valeur des points',
                'verbose_name_plural': 'Valeurs des points',
                'db_table': 'loyalty_point_values',
            },
        ),
    ]
