# Generated by Django 5.2.15 on 2026-06-26 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_discount_price_product_order_count'),
        ('commandes', '0004_alter_order_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.productvariant'),
        ),
    ]
