# Generated by Django 6.0.6 on 2026-08-06 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_product_discount_price_product_order_count"),
        ("commandes", "0010_orderpack"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="orderpack",
            new_name="commandes_o_order_i_98538f_idx",
            old_name="commandes_o_order_i_626871_idx",
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="catalog.productvariant"
            ),
        ),
    ]
