# Generated by Django 5.2.15 on 2026-06-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='order_count',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, help_text='Nombre de commandes contenant ce produit (recalculé par signal).'),
        ),
    ]
