# Generated by Django 6.0.6 on 2026-08-12 13:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "last_name",
                    models.CharField(max_length=150, verbose_name="Last Name"),
                ),
                (
                    "first_name",
                    models.CharField(max_length=150, verbose_name="First Name"),
                ),
                ("city", models.CharField(max_length=150, verbose_name="City")),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="reviews/profiles/",
                        verbose_name="Profile Image",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        verbose_name="Rating",
                    ),
                ),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "is_approved",
                    models.BooleanField(default=True, verbose_name="Approved"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
            ],
            options={
                "verbose_name": "Customer Review",
                "verbose_name_plural": "Customer Reviews",
                "ordering": ["-created_at"],
            },
        ),
    ]
